### ISSUE TITLE
Redesign "Look n' Feel"

### ISSUE THREAD

**Issue by HarryRybacki-zz** [cos-labs/scinet#12]
Need to sit down with an experienced ui designer to refactor.
- [CSL](https://github.com/citation-style-language/schema/blob/master/csl-data.json) has _a lot_ of optional fields. How do we make them available without being intrusive?

**Comment by lyndsysimon** [comment]
I'm a fan of the ComboBox, because it offers the ability to allow an arbitrary number of options without taking up more space than a single input on a form. Unfortunately it is only available in HTML starting with version 5. It's not well-supported by legacy browsers.

Here's a [proprietary implementation](http://demos.kendoui.com/web/combobox/index.html) and [here's a discussion of how it is done in HTML5 and can be emulated in older browsers](http://www.scriptol.com/html5/combobox.php).
