### ISSUE TITLE
Create startup script to automate AWS startup/execution

### ISSUE THREAD

**Issue by HarryRybacki-zz** [cos-labs/scinet#27]
- Document!

**Comment by robchambers** [comment]
Harry - 
What needs to be done here? I'd guess...
Make sure that MongoDB is automatically started as a service w/ proper configuration options...
Make sure that Flask is registered as http server
Anything I'm missing?

Are you planning to run mongo and flask on separate servers or the same servers?

**Comment by HarryRybacki-zz** [comment]
You hit the head of the nail. For now they can run on the same server. However, as we expand the project we will certainly distribute this across several.

**Comment by HarryRybacki-zz** [comment]
@robchambers We've got crowdscholar and citelet running on separate EC2 instances now and they are able to communicate. You did a great job with the documentation. Permamounting the EBS volume and setting up the nginx/uWSGI stuff was incredibly helpful. Would you be interested/do you have time to put together a script to automate this?

**Comment by robchambers** [comment]
I am interested in doing this, and I can hop on it quickly, but I would need a very specific description of exactly what's needed. As of now, I don't have a clear vision of what the automation script will do. 

It seems like Lindsy and/or Jeff have some specific ideas of how this should be done (which is great, because I have none! :)  and if I'm going to spend time to do this, I'd like to make sure it's exactly what you want, and learn how to do things the right way.

What would make this work for me is knowing:
- what the scope of the scripts is (i.e., just for development servers, or do we need separate development/staging/production... and is this startup/shutdown, or do we need steps for data backup, etc. etc. ).
- what tools to use (i heard something like Salt mentioned, and I know there are other tools, to automate the devops stuff). I want to use the best tools, and I want to use the ones that you guys have experience with.
- absolutely any other advice that anyone has on how to do this.

Then, I'll be happy to figure out the rest on my own and document it.

Rob
